#' cutLimit - Identify the minimum index of parameter values to eliminate
#'
#' This function locates the minimum number of paramter/state variables that
#' must be eliminated base upon performance in order to decrease the domain
#' of the parameter by a specified percentage amount. This function links
#' performance of the y-values. Dependent on domainSize() function.
#' 
#' 
#' @param decay.seq Decay sequence generated by paramDecay(surface.x, surface.y)
#' @param threshold Percentage threshold by which one wants the domain limited
#' 
#' 
#' @return The identity of the minimum number of parametere state values that must be
#' eliminated based on performance to decrease the parameter domain by threshold percent
#' @export
#'

cutLimit <- function(surface.x, decay.seq, threshold){
  newDomain <- domainSize(surface.x)*(1-threshold)
  minValue <- min(which(decay.seq < newDomain))
  return(minValue)
}
